

import java.sql.*;
import java.util.*;
import java.io.*;
import java.math.BigInteger;
import java.net.*;


public class a1 extends javax.swing.JFrame {

    /** Creates new form a1 */
    public a1() {
        initComponents();
    }
Vector v=new Vector();


  public static String x,path_available="no",attack_node="no";
public static int w;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        a1_attack = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A1_PEER");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("CLIENT");
        jLabel2.setBounds(290, 30, 160, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel3.setText("Received Messages");
        jLabel3.setBounds(40, 90, 250, 40);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane1.setBounds(120, 140, 530, 96);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField1.setBounds(180, 370, 420, 30);
        jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(80, 380, 67, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Feedback");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(250, 430, 130, 40);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("send");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(450, 430, 100, 30);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GROUP" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.setBounds(200, 280, 150, 40);
        jLayeredPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PEER " }));
        jComboBox2.setBounds(390, 280, 150, 40);
        jLayeredPane1.add(jComboBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        a1_attack.setText("d");
        a1_attack.setBounds(580, 40, 120, 20);
        jLayeredPane1.add(a1_attack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setText("Activate");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(520, 80, 100, 23);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setText("Deactivate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(640, 80, 110, 23);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/BAC.jpg"))); // NOI18N
        jLabel1.setBounds(-6, 4, 780, 490);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fbsend();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        group();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        send();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
            try{
           Class.forName("oracle.jdbc.OracleDriver");
    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/orcl","system","system");
    Statement stmt=conn.createStatement();
    int o_flag=0;
      ResultSet rs= stmt.executeQuery("select * from atr where name ='a1' ");
    
     while(rs.next())
    {
        
              String h=       rs.getString(1);
            o_flag =1 ;
             
             
    }  
    
    
    
    if(o_flag!=1)
    {
       stmt.executeUpdate("insert into atr values('a1')");
      
    }   
        a1_attack.setText("a");
      
        
        
        }
       catch(Exception uti) {
       
       
       System.out.println(uti+"attack insert exception");
       }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try{
           Class.forName("oracle.jdbc.OracleDriver");
    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/orcl","system","system");
    Statement stmt=conn.createStatement();
    
     
    stmt.executeQuery("delete from atr where name ='a1' ");
    
 
    
    
    
   
      
        
        }
       catch(Exception uti) {
       
       
       System.out.println(uti+"attack insert exception");
       }
        
        a1_attack.setText("d");
    }//GEN-LAST:event_jButton5ActionPerformed
 
    
    
    
    
    
    
    
    
    
    
    
    
    
    
       
     
     
     
      public void fbsend()
    {
        try
        {
            
                       
    
     
             s=new Socket("localhost",6000);
            System.out.println("connect");
        ObjectOutputStream out=new ObjectOutputStream(s.getOutputStream());
          Vector a = new Vector() ;
       a.add(0,"fb");
       a.add(1,jTextField1.getText());
       
       out.writeObject(a);
       
       
       
       
        ObjectInputStream inn=new ObjectInputStream(s.getInputStream());
                        String b =(String) inn.readObject();
                        System.out.println(b);
    
	out.flush();
	out.close();
	s.close();
        
        
                
        
        }
        catch( Exception exe)
        {
            System.out.println(exe+"fbex");
        }
    }
     
     
     
     
     
     
      
      
      
      
      
      
      
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
     Socket s;
     public void send()
    {
        
        
        
        
        
        fg();
        
        
        if( path_available.equals("yes"))
        {
        
        path_available="no";
        
        try
        {
            
                          Class.forName("oracle.jdbc.OracleDriver");
    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/orcl","system","system");
    Statement stmt=conn.createStatement();
    
    
    
    
    
    
    
    
    
     stmt.executeUpdate("insert into sensor_db values('a1','"+jComboBox2.getSelectedItem().toString()+"','"+jTextField1.getText()+"')");
     
    ResultSet rs=stmt.executeQuery("select * from registering where pname='"+jComboBox2.getSelectedItem().toString()+"'");
     while(rs.next())
    {
        
   x  =rs.getString(2);
   
   w  =Integer.parseInt(rs.getString(3)); 
   
   System.out.println("hi"+x+"+\t"+w);
   
    }     
             s=new Socket(x,w);
            System.out.println("connect");
        ObjectOutputStream out=new ObjectOutputStream(s.getOutputStream());
          Vector a = new Vector() ;
       a.add(0,"hi");
       
        String ss=jTextField1.getText();
        long keyval1=1269;
			    ECIES crypt;



	            ECDomainParameters dp = ECDomainParameters.NIST_B_163();
            	ECPrivKey skA = new ECPrivKey(dp, BigInteger.valueOf(keyval1));
				System.out.println("the value skA is  "+skA);
                            
				ECPubKey pkA = new ECPubKey(skA);
                                System.out.println(ss);
				crypt = new ECIES(skA, pkA, ss.getBytes()); // encrypt the data
				    System.out.println("the encrypted value is "+crypt);
       a.add(1,ss);
    
       out.writeObject(a);
       
       
       
       
        ObjectInputStream inn=new ObjectInputStream(s.getInputStream());
                        String b =(String) inn.readObject();
                        System.out.println(b);
    
	out.flush();
	out.close();
	s.close();
        
        
        
        
        
        
        
        
        
        
        
        
        
        }
        catch( Exception exe)
        {
            System.out.println(exe+"");
        }
    }
        
        
        else{
        
        jTextArea1.setText("no paths available");
        
        
        }
    }
    
    public void fg()
    {
    try{
         Class.forName("oracle.jdbc.OracleDriver");
    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/orcl","system","system");
    Statement stmt=conn.createStatement();
Connection conn1=DriverManager.getConnection ("jdbc:oracle:thin:@//localhost:1521/orcl","system","system");
    Statement stmt1=conn1.createStatement();
    
    
    ResultSet rs2;
    
    
    
        
    ResultSet rs=stmt.executeQuery("select * from pathfound ");
     while(rs.next())
    {
        String y =rs.getString(2);
    String[] ht  =y.split(">");
    
   
    int re =Integer.parseInt(rs.getString(3)); 
   
    
    
    
    String s12 = jComboBox2.getSelectedItem().toString();
    
    
    
    if((ht[ht.length-1].equals(s12)))
    {
        if(ht[0].equals("a1"))
        {
            path_available="yes";
        
        for(int i=0 ;i< ht.length;i++)
        {
             

 rs2=stmt1.executeQuery("select * from atr");
     while(rs2.next())
    {
System.out.println("\n enter");
String att =rs2.getString(1);
       if(att.equals(ht[i]))
{
System.out.println("\n check");

             if(!ht[i].equals("a1"))
{

           jTextArea1.append("\tattacking node found"+ht[i]);

}
  }         

}           



jTextArea1.append("\t>"+ht[i]);
              
        }
            jTextArea1.append("\n");
        }
    }
    
    }     
        
    
    
    }
    catch(Exception ur)
    {
    System.out.println(ur+"\nur exception ");
    
    }    
    }
      
     
  ServerSocket ss;
      
    public void sstart()
    {
       
     
         try{
       
             
             
             
             
      ss =new ServerSocket(5001);
        String data;
         System.out.println("listening");
         
         while(true)
         {
              s=ss.accept();

         // jTextArea1.append(s.toString());
         
	ObjectInputStream inn=new ObjectInputStream(s.getInputStream());
   Vector   b=(Vector)inn.readObject();
      System.out.println("the received values is"+b);
     String bb=b.get(1).toString();
     long keyval1=1269;
     ECDomainParameters dp = ECDomainParameters.NIST_B_163();
			ECPrivKey skA = new ECPrivKey(dp, BigInteger.valueOf(keyval1));
     DerIOBuffer der = new DerIOBuffer(bb.getBytes());
					ECIES decrypt = der.toECIES();
					byte[] pt1 = decrypt.decrypt(skA); // decrypt the data
					String str1 = new String(pt1);
					System.out.println("the data is"+str1);
     
     
      jTextArea1.append("\n"+str1);
         
         
     if(bb.equals("close"))
     {
         this.setVisible(false);
     }
         
     ObjectOutputStream dis=new ObjectOutputStream(s.getOutputStream());
     dis.writeObject("ack");
   
         }
        }
        catch(Exception e)
        {
           System.out.println(e); 
        }
    }
  
    public void refresh()
    {
        
        
            jComboBox1.removeAllItems();
          jComboBox2.removeAllItems();
    
    try
    {
    
    Class.forName("oracle.jdbc.OracleDriver");
    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/orcl","system","system");
    Statement stmt=conn.createStatement();
    ResultSet rs=stmt.executeQuery("select * from registering");
    while(rs.next())
    {
       
    String s1=rs.getString(4);
    
    if(!v.contains(s1))
        v.add(s1);
    
    }
      System.out.println(v);


  for(int i=0;i<=v.size();i++)
  {
      
   jComboBox1.addItem(v.get(i)+"");
    jComboBox2.addItem(v.get(i)+"");
    
   System.out.println(i);
  } 

    }
    catch(Exception ref)
    {
    System.out.println(ref+"\trefresh exception");
    }
 
    }

   
 String q;
    public void group()
    {
        
          try
    {
     jComboBox2.removeAllItems();
    Class.forName("oracle.jdbc.OracleDriver");
    DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
    Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@//localhost:1521/orcl","system","system");
    Statement stmt=conn.createStatement();
    
        q="select * from registering where pgroup ='"+jComboBox1.getSelectedItem().toString()+"'";
    
    
        ResultSet rs=stmt.executeQuery(q);
    while(rs.next())
    {
        String s1 = rs.getString(1);
          String s2 = rs.getString(2);
            String s3 = rs.getString(3);
              String s4 = rs.getString(4);
        
     jComboBox2.addItem(s1);
    }
    
    
     
    stmt.close();
    conn.close();
    }
    catch(Exception e)
    {
        System.out.println("error"+e);
    }
    
 
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
            
        a1 bb=new a1();
           bb.setVisible(true);
        bb.sstart();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1_attack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
